###
POST http://{{url}}/http
Content-Type: application/json

{
  "path" : "/account/admin@admin",
  "method" : "GET"
}
###

###
POST http://{{url}}/http
Content-Type: application/json

{
  "path" : "/account/exists/admin@admin",
  "method" : "GET"
}
###