apiVersion: v1
kind: Pod
metadata:
  name: kao-note-front-end
spec:
  containers:
    - name: kao-note-front-end-container
      image: taykita/kaonote:kao-note-front-end
      ports:
        - containerPort: 8080
      env:
        - name: SPRING_PROFILES_ACTIVE
          value: "DEV"
    - name: kao-gateway
      image: taykita/kaonote:kao-note-gateway
      ports:
        - containerPort: 7856
      env:
        - name: SPRING_PROFILES_ACTIVE
          value: "DEV-FRONT"
